//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrnekE_Ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasketProduct
    {
        public int BasketID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> ProductCount { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual Product Product { get; set; }
    }
}
